### ISSUE TITLE
Autorole Feature

### ISSUE THREAD

**Issue by Montori** [Gerald-Development/Barista-Gerald#73]
Administrators of a guild should be able to configure roles that are given to new people upon joining the server.
Multiple Roles should be applicable for that feature.
Roles should be added, removed and displayed in an embed.
Max. Roles: 10

Existing members should not get the roles yet. We need to think of an efficient solution for that.

**Comment by Montori** [comment]
Until we implement the new pipeline this issue is to be implemented in the current weekly branch (2021-20B)

**Comment by Scot-Survivor** [comment]
An efficient solution for bulk role applying should be to do 10 members every 20 seconds till the server is done. These numbers can be changed to whatever you think is necessaracy. Just an idea I am not fully aware if this would work in practice.
